### ISSUE TITLE
HTML Tags

### ISSUE THREAD

**Issue by Kaffiend** [DataByne/Monokai-HighContrast#8]
This theme would be perfect if only the actual html tags were a different color than the attributes.
![image](https://user-images.githubusercontent.com/7826229/28235915-ab647a2e-68e6-11e7-903a-da0c315eaa55.png)
They can be hard to differentiate for low vision users.
This snip is from the plain monokai theme
![image](https://user-images.githubusercontent.com/7826229/28235938-235f9748-68e7-11e7-9abb-73c7b856fe8f.png)

Attribute values are fine the way they are, and the attribute names are fine, as long as the tags change :smile:

**Comment by DataByne** [comment]
I agree. Right now there aren't any real hooks for markup, so I'll get to adding them.

**Comment by DataByne** [comment]
Update v1.1.0 fixes this!
